### ISSUE TITLE
Use profiles.json instead of syntaxProfiles.json

### ISSUE THREAD

**Issue by vegetableman** [emmetio/emmet#369]
@sergeche pretty cool project :+1: . Been using emmet on atom. Found a little bug. Only when `profiles.json` is added instead of `syntaxProfiles.json` to the `~/emmet` directory, does customisation of profiles work.

Also, Digging further, the code seems to consider extending the default profile only when the key is `profiles`, https://github.com/emmetio/emmet/blob/master/lib/emmet.js#L219

An example:
Using below on `syntaxProfiles.json` does not work but works when added to `profiles.json`.

``` json
{
 "html": {
    "tag_case": "upper",
    "filters": "html, e",
    "attr_quotes" : "single"
  }
}
```

Issue faced on:-
https://github.com/emmetio/emmet-atom/issues/68. (the plugin simply calls loadExtensions with the file list)
##

**Comment by sergeche** [comment]
There’s additional call for loading `syntaxProfiles.json`: https://github.com/emmetio/emmet/blob/master/lib/emmet.js#L226

Will investigate this issue as soon as I have time.

**Comment by vegetableman** [comment]
Adding line ```profile.create(name, normalizeProfile(profiles[name]));``` to ```loadSyntaxProfiles``` would do as well, but yeah, you would know a better approach.

**Comment by sheriffderek** [comment]
You guys implement this already? My `syntaxProfiles.json` seems to be reading just fine now.

**Comment by brunowego** [comment]
+1

**Comment by sjelfull** [comment]
I read emmetio/emmet-atom#68 before coming here.

@vegetableman Have you gotten your mentioned solution there to work? I'm on Emmet 2.3.14, and i've done the following:

1. Set the custom extensions path in settings to the following: ~/.atom-custom/emmet/
2. Inside of emmet/ folder, i've tried adding the following files after the previous one didn't work: profiles.json, syntaxProfiles.json, preferences.json.
3. The content of profiles/syntaxProfiles.json is the following:
```
{
    "html": {
        "filters": "html, c",
    }
}
```

I've also tried to add the files to ~/emmet, without success.

**Expected behaviour:** On expanding a html tag, like *.container*, I'd expect the following result: 
```
<div class="container"></div>
<!-- /.container -->
```
**Current behaviour:** Results in `<div class="container"></div>` without the comment. Adding the |c filter manually works.

**Comment by sergeche** [comment]
>  I'm on Emmet 2.3.14

The latest version of Emmet is 2.4.1

**Comment by sjelfull** [comment]
Updated. No change in behaviour, though.

**Comment by sergeche** [comment]
Check out DevTools console for possible errors. I’ve fixed similar issue in v2.4.0

**Comment by sjelfull** [comment]
No errors in DevTools.

![Dev tools screenshot](https://storage.jumpshare.com/preview/vBoFVIVoV0khcHfRgJaNNvNWpOzAuzcBly-lK0G6yffTZwvmz08tveJtRJ9P-LH4Bbk7tOfmeaOsywLoEQIHt38t7wA9n-vlT_jkylN98IjJmZ_gxzDuijCC6OnKLtdF)

**Comment by sergeche** [comment]
If this is the content of your `syntaxProfiles.json`:
```json
{
    "html": {
        "filters": "html, c",
    }
}
```

then there’s an error: trailing comma after `filter` value so this code is invalid JSON. Just checked `syntaxProfiles.json` with correct contents on Emmet v2.4.1 — everything works as expected after restarting Atom

**Comment by sjelfull** [comment]
Ah, of course! Thank you!

**Comment by nikini** [comment]
I stil can't get it to work. I added `syntaxProfiles.json` to the packages/emmet folder but it still doesn't work

**Comment by sergeche** [comment]
@nikini it’s not `packages/emmet` folder, it should be `~/emmet` and `~` in UNIX systems means you HOME folder

**Comment by nikini** [comment]
@sergeche I was using atom and I though it was an atom thing. Now it works :+1: Awesome :)

**Comment by JeremyBYU** [comment]
What if you are using windows?  I don't see any emmet folder in my Home directory nor in my Application Data directory.

**Comment by sergeche** [comment]
@JeremyBYU hmm, may you should create it? :)

**Comment by sergeche** [comment]
Not relevant anymore, Emmet config will be moved to web UI
